---
- name: Enable and start cockpit socket
  systemd:
    name: cockpit.socket
    enabled: true
    state: started

- name: Enable and start libvirtd
  systemd:
    name: libvirtd
    enabled: true
    state: started

- name: Set libvirt default network to autostart
  community.libvirt.virt_net:
    name: default
    autostart: true

- name: Start libvirt default network
  community.libvirt.virt_net:
    name: default
    state: active

- name: Define vms storage pool
  community.libvirt.virt_pool:
    name: vms
    command: define
    xml: |
      <pool type='dir'>
        <name>vms</name>
        <target>
          <path>/srv/vms</path>
        </target>
      </pool>

- name: Set vms storage pool to autostart
  community.libvirt.virt_pool:
    name: vms
    autostart: true

- name: Start vms storage pool
  community.libvirt.virt_pool:
    name: vms
    state: active
