---
- name: Restart nginx
  community.docker.docker_container:
    name: nginx
    state: started
    restart: true

- name: Restart diun
  community.docker.docker_container:
    name: diun
    state: started
    restart: true
